alias ls='ls --color'
alias l='ls -lLhXB --time-style=+"%Y-%m-%d %T"'
alias ll='ls -alh --time-style=+"%Y-%m-%d %T"'
alias ..='cd ..'
alias ...='cd ../..'
alias used='du * -sBM | sort -nr | head'
alias o='less -N'
alias v='view'
alias grep='grep -In --color=auto --exclude-dir={.bzr,CVS,.git,.hg,.svn} --exclude="*~" --exclude-dir=".git" --exclude-dir=".idea"'
alias tcplisten='lsof -i tcp -P | grep LISTEN'
alias py='python3'
alias ps='ps -lf -U $(id -u)'
alias glol='git log --graph --pretty='\''%Cred%h %Cgreen%ci%x08%x08%x08%x08%x08%x08%Creset -%C(yellow)%d%Creset %s %C(bold blue)<%an>%Creset'\'' --abbrev-commit'
alias gmnoff='git merge --no-ff'
alias glola='glol --all'
alias glolb='glol --branches'

alias d='docker'
alias dn='docker network'
alias di='docker image'
alias dis='docker images'
alias dipr='docker image prune'
alias dirm='docker rmi'
alias dbu='docker build'
alias dco='docker container'
alias dcopr='docker container prune'
alias dcos='docker container ls'
alias dps='docker ps --format "table {{.ID}}    {{.Names}}\t{{.Ports}}\t{{.Image}}\t{{.Status}}\t{{.Command}}"'
alias dpsa='dps -a'
alias dpsexited='dps -f status=exited'
alias dr='docker run'
alias dcp='docker-compose'
alias dcpclean='docker-compose down --rmi all'
alias de='docker exec'
alias dk='docker kill'
alias deit='docker exec -it'

alias k='kubectl'
